#!/bin/sh
set -e

echo "[GeniusDock::Prolog-Blockly] Starting prolog-blockly..."

cd /app

CORES=$(nproc)

echo "[GeniusDock::Prolog-Blockly] Using docker client $(docker -v)"
echo "[GeniusDock::Prolog-Blockly] Checking docker connection...."
export DOCKER_HOST='tcp://localhost:2375'
docker version

echo "[GeniusDock::Prolog-Blockly] Server is listening on all interfaces (0.0.0.0). Concurrency level is $CORES"
bundle exec puma -t $CORES:$(expr 2 \* 3  \* 4 \* $CORES) -p 3001
