#!/bin/bash
set -e

echo "[GeniusDock::Prolog-Blockly] Starting prolog-blockly..."

cd /app

echo "[GeniusDock::Prolog-Blockly] Using docker client $(docker -v)"
echo "[GeniusDock::Prolog-Blockly] Checking docker connection...."
export DOCKER_HOST='tcp://localhost:2375'
docker version

echo "[GeniusDock::Prolog-Blockly] Downloading mumuki plunit worker..."
docker pull mumuki/mumuki-plunit-worker:2.0

echo "[GeniusDock::Prolog-Blockly] Server is listening on all interfaces (0.0.0.0)."
bundle exec rackup -p 3001
